import intro
from time import sleep
import os
import pygame
from Music_sounds import *

pygame.init()

def About():
    about_theme.play(0)
    os.system('cls')
    print("")
    sleep(0.3)
    print("                                                      À Propos")
    sleep(0.3)
    print("""
                                                        ,-.                               
                                   ___,---.__          /'|`\          __,---,___          
                                ,-'    \`    `-.____,-'  |  `-.____,-'    //    `-.       
                              ,'        |           ~'\     /`~           |        `.      
                             /      ___//              `. ,'          ,  , \___      \    
                            |    ,-'   `-.__   _         |        ,    __,-'   `-.    |    
                            |   /          /\_  `   .    |    ,      _/\          \   |   
                            \  |           \ \`-.___ \   |   / ___,-'/ /           |  /  
                             \  \           | `._   `\\  |  //'   _,' |           /  /      
                              `-.\         /'  _ `---'' , . ``---' _  `\         /,-'     
                                 ``       /     \    ,='/ \`=.    /     \       ''          
                                         |__   /|\_,--.,-.--,--._/|\   __|                  
                                         /  `./  \\`\ |  |  | /,//' \,'  \                  
    ██╗     ███████╗    ██████╗ ██████╗ ██╗███╗   ██╗ ██████╗███████╗\   ██████╗ ███████╗███╗   ███╗ ██████╗ ███╗   ██╗
    ██║     ██╔════╝    ██╔══██╗██╔══██╗██║████╗  ██║██╔════╝██╔════╝ \  ██╔══██╗██╔════╝████╗ ████║██╔═══██╗████╗  ██║
    ██║     █████╗      ██████╔╝██████╔╝██║██╔██╗ ██║██║     █████╗    \ ██║  ██║█████╗  ██╔████╔██║██║   ██║██╔██╗ ██║
    ██║     ██╔══╝      ██╔═══╝ ██╔══██╗██║██║╚██╗██║██║     ██╔══╝    | ██║  ██║██╔══╝  ██║╚██╔╝██║██║   ██║██║╚██╗██║
    ███████╗███████╗    ██║     ██║  ██║██║██║ ╚████║╚██████╗███████╗  | ██████╔╝███████╗██║ ╚═╝ ██║╚██████╔╝██║ ╚████║
    ╚══════╝╚══════╝    ╚═╝     ╚═╝  ╚═╝╚═╝╚═╝  ╚═══╝ ╚═════╝╚══════╝  | ╚═════╝ ╚══════╝╚═╝     ╚═╝ ╚═════╝ ╚═╝  ╚═══╝
                                       |   |     /'\_\_\ | /_/_/`\     |   |                 ver. demo
                                        \   \__, \_     `~'     _/ .__/   /            
                                         `-._,-'   `-._______,-'   `-._,-'



                          """)
    sleep(0.3)
    print("")
    sleep(0.3)
    print("")
    sleep(0.3)
    print("")
    sleep(0.3)
    print("")
    sleep(0.3)
    print("")
    sleep(0.3)
    print("")
    sleep(0.3)
    print("")
    sleep(0.3)
    print("")
    sleep(0.3)
    print("")
    sleep(0.3)
    print("")
    sleep(0.3)
    print("")
    sleep(0.3)
    print("")
    sleep(0.3)
    print("")
    sleep(0.3)
    print("                                             Ce jeu vous est présenté par ")
    sleep(0.3)
    print("                                                 NotPirates Studios")
    sleep(0.3)
    print("")
    sleep(0.3)
    print("")
    sleep(0.3)
    print("")
    sleep(0.3)
    print("")
    sleep(0.3)
    print("")
    sleep(0.3)
    print("")
    sleep(0.3)
    print("")
    sleep(0.3)
    print("")
    sleep(0.3)
    print("")
    sleep(0.3)
    print("")
    sleep(0.3)
    print("")
    sleep(0.3)
    print("             SYSTEME DE COMBAT, SOUND DESIGN, VISUELS, GAME DESIGN ")
    sleep(0.3)
    print("                                             et plein d'autres choses")
    sleep(0.3)
    print("")
    sleep(0.3)
    print("                                                                                                 Dorian CANONNE")
    sleep(0.3)
    print("")
    sleep(0.3)
    print("")
    sleep(0.3)
    print("")
    sleep(0.3)
    print("             SYSTEME D'INVENTAIRE, D'EQUIPEMENT, DE GESTION DES DONNEES")
    sleep(0.3)
    print("                                             et plein d'autres choses")
    sleep(0.3)
    print("")
    sleep(0.3)
    print("                                                                                                 Gabriel GOLDBRONN")
    sleep(0.3)
    print("")
    sleep(0.3)
    print("")
    sleep(0.3)
    print("")
    sleep(0.3)
    print("             LOREMESTRE, WORLDMAP DESIGNER, WORLD BUILDER")
    sleep(0.3)
    print("                                             et plein d'autres choses")
    sleep(0.3)
    print("")
    sleep(0.3)
    print("                                                                                                 Argan DELAIRE")
    sleep(0.3)
    print("")
    sleep(0.3)
    print("")
    sleep(0.3)
    print("")
    sleep(0.3)
    print("                                                          MUSIQUES")
    sleep(0.3)
    print("")
    sleep(0.3)
    print("                                  Mattashi - The Final Battle [Epic 8-Bit Orchestral Battle]")
    sleep(0.3)
    print("                                          Parks and Recreation title music (8-bit)")
    sleep(0.3)
    print("                                            Yoshi's Island OST - CAVE THEME 8 BIT")
    sleep(0.3)
    print("                                  Daughter of the Dark God [8-Bit; VRC6] - Octopath Traveler")
    sleep(0.3)
    print("                                                 Lufia 2 OST: Boss battle theme")
    sleep(0.3)
    print("                                             (8-bit Remix) Bakamitai - Yakuza 0")
    sleep(0.3)
    print("                               Tonight Stars an Easygoing Egoist (Gameboy ver.) ~ Egoistic Flowers")
    sleep(0.3)
    print("                                       Teenage Mutant Cirno Turtle [FamiTracker]")
    sleep(0.3)
    print("                                      Decisive Battle II [8-Bit; VRC6] - Octopath Traveler")
    sleep(0.3)
    print("                                         Demon's Crest OST: Memorial of the Fallen Ones")
    sleep(0.3)
    print("                                                ChipBoy - Professional Fight!")
    sleep(0.3)
    print("                                              Super Metroid OST : Lower Brinstar ")
    sleep(0.3)
    print("                                       Beethoven - 8-bit Symphony No. 7 - 2. Allegretto")
    sleep(0.3)
    print("                                                hystericalgamer - Boss Battle")
    sleep(0.3)
    print("")
    sleep(0.3)
    print("")
    sleep(0.3)
    print("")
    sleep(0.3)
    print("                                                     Remerciements aux")
    sleep(0.3)
    print("                                                         TESTEURS :")
    sleep(0.3)
    print("")
    sleep(0.3)
    print("")
    sleep(0.3)
    print("")
    sleep(0.3)
    print("")
    sleep(0.3)
    print("")
    sleep(0.3)
    print("")
    sleep(0.3)
    print("")
    sleep(0.3)
    print("")
    sleep(0.3)
    print("")
    sleep(0.3)
    print("")
    sleep(0.3)
    print("")
    sleep(0.3)
    print("")
    sleep(0.3)
    print("                                     Remerciements speciaux à notre intervenant LOÏC JANIN ")
    sleep(0.3)
    print("                                         pour la qualité de ses cours et sa sympathie.")
    sleep(0.3)
    print("")
    sleep(0.3)
    print("")
    sleep(0.3)
    print("")
    sleep(0.3)
    print("")
    sleep(0.3)
    print("")
    sleep(0.3)
    print("")
    sleep(0.3)
    print("")
    sleep(0.3)
    print("")
    sleep(0.3)
    print("")
    sleep(0.3)
    print("")
    sleep(0.3)
    print("")
    sleep(0.3)
    print("")
    sleep(0.3)
    print("")
    sleep(0.3)
    print("")
    sleep(0.3)
    print("")
    sleep(0.3)
    print("")
    sleep(0.3)
    print("")
    sleep(0.3)
    print("")
    sleep(0.3)
    print("")
    sleep(3.0)
    os.system("cls")
    from intro import titlebis
    titlebis()
    return