import pygame
pygame.init()

pygame.mixer.music.set_volume(5.0)

sand_low_blow = pygame.mixer.Sound("music/sand_lowblow.wav")
beginning_music = pygame.mixer.Sound("music/intro_narration.ogg")
tutorial_music = pygame.mixer.Sound("music/tutorial_fight.ogg")
text_sound = pygame.mixer.Sound("music/text.ogg")
intro_music = pygame.mixer.Sound("music/intro.ogg")
intro_music_bis = pygame.mixer.Sound("music/introbis.ogg")
validation_sound = pygame.mixer.Sound("music/ok_sound.wav")
combat_music = pygame.mixer.Sound("music/field_fight.ogg")
about_theme = pygame.mixer.Sound("music/about_music.ogg")
combat_music = pygame.mixer.Sound("music/field_fight.ogg")
sword_sound = pygame.mixer.Sound("music/coup.wav")
fork_sound = pygame.mixer.Sound("music/coup_fourche.wav")
enemy_death = pygame.mixer.Sound("music/ennemi_mort.wav")
evil_beam_spell = pygame.mixer.Sound("music/evil_beam.wav")
absorbtion_soundeffect = pygame.mixer.Sound("music/absorbtion_sound.wav")
absorbtion_gain_hp = pygame.mixer.Sound("music/heal_spell.wav")
jingle = pygame.mixer.Sound("music/jingle.ogg")
crack = pygame.mixer.Sound("music/bone_crack.ogg")
broken_armor = pygame.mixer.Sound("music/broken_armor.ogg")
broken_weapon = pygame.mixer.Sound("music/broken_weapon.ogg")
acid_sound = pygame.mixer.Sound("music/acid.ogg")
combat_music_2 = pygame.mixer.Sound("music/decisive_battle.ogg")
menu_sound = pygame.mixer.Sound("music/choice_sound.ogg")
quest_sound = pygame.mixer.Sound("music/quest_sound.wav")
demo_intro_sound = pygame.mixer.Sound("music/demo_intro_sound.ogg")
demo_deva_combat = pygame.mixer.Sound("music/deva_figght.ogg")
king_scream = pygame.mixer.Sound("music/roi_demon_cri.ogg")
gates_music = pygame.mixer.Sound("music/demo_music_gates.ogg")
questdonesound = pygame.mixer.Sound("music/finished_quest_sound.ogg")
king_scream = pygame.mixer.Sound("music/king_scream.ogg")
seism_sound = pygame.mixer.Sound("music/seism.ogg")
war_horn = pygame.mixer.Sound("music/war_horn.ogg")
ulric_theme = pygame.mixer.Sound("music/ulric_theme.ogg")
throne_theme = pygame.mixer.Sound("music/throne_theme.wav")
citadel_walk = pygame.mixer.Sound("music/citadel_walk.wav")
light_beam = pygame.mixer.Sound("music/light_beam.wav")
light_attack = pygame.mixer.Sound("music/light_attack.wav")
final_boss_theme = pygame.mixer.Sound("music/final_boss_theme.wav")
battle_sound_effect = pygame.mixer.Sound("music/battle_sound.ogg")
narration_intro_music = pygame.mixer.Sound("music/demo_intro_narration.ogg")
wind_thunder_sound = pygame.mixer.Sound("music/Thunderstorm.ogg")
bakamitai = pygame.mixer.Sound("music/bakamitai.ogg")
